#!/usr/bin/env python3
"""Produce test vectors from the real `audible` Python package.

The TypeScript Audible client is a port. A port is only as good as the
evidence that it agrees with the original, and the parts that matter —
PKCE, the OAuth URL, the ADP request signature, the licence voucher — cannot
be checked against a live account in CI. So they are checked against the
package that is known to work.

    python3 -m venv /tmp/audible-vectors
    /tmp/audible-vectors/bin/pip install audible==0.12.0 cryptography
    /tmp/audible-vectors/bin/python scripts/generate-audible-vectors.py

The output is committed as test/resources/audible-vectors.json, so the tests
need neither Python nor a network. Regenerate it if the pinned `audible`
version changes.

No secret is written: the RSA private key is generated for this run and only
its *public* half is recorded, which is enough for the tests to verify a
signature Python produced.
"""

import base64
import hashlib
import json
import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "test/resources/audible-vectors.json"

# Fixed, obviously fake inputs. Nothing here belongs to a real account.
SERIAL = "8B0FCA1B2E7D4A5C9F3E1D0A6B4C8E2F"
VERIFIER = b"tK9_fake-code-verifier-for-tests_Qz1"
DEVICE_TYPE = "A2CZJZGLK2JJVM"
DEVICE_SERIAL = "3F7A1C5E9B2D4068A1C3E5F7091B2D4C"
CUSTOMER_ID = "amzn1.account.EXAMPLEFAKEUSERID000000"
ASIN = "B0EXAMPLE1"
SIGN_DATE = "2026-01-02T03:04:05.678901+00:00Z"


def main() -> None:
    try:
        from audible.aescipher import _decrypt_voucher
        from audible.auth import sign_request
        from audible.localization import Locale
        from audible.login import build_client_id, build_oauth_url, create_s256_code_challenge
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
    except ImportError as exc:
        sys.exit(f"needs the audible package and cryptography in this interpreter: {exc}")

    vectors: dict = {"_comment": "Generated by scripts/generate-audible-vectors.py"}

    # --- PKCE and the OAuth URL -----------------------------------------
    vectors["pkce"] = {
        "verifier": VERIFIER.decode(),
        "challenge": create_s256_code_challenge(VERIFIER).decode(),
    }
    vectors["clientId"] = {"serial": SERIAL, "clientId": build_client_id(SERIAL)}

    vectors["oauthUrls"] = {}
    for marketplace in ("de", "us", "uk", "jp"):
        locale = Locale(marketplace)
        url, _ = build_oauth_url(
            country_code=locale.country_code,
            domain=locale.domain,
            market_place_id=locale.market_place_id,
            code_verifier=VERIFIER,
            serial=SERIAL,
            with_username=False,
        )
        vectors["oauthUrls"][marketplace] = url

    # --- Request signing -------------------------------------------------
    # An ephemeral key: only the public half is recorded, so the fixture holds
    # nothing secret and the test can still verify Python's own signature.
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    public_pem = (
        key.public_key()
        .public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        .decode()
    )

    adp_token = "{enc:fake}{key:fake}{iv:fake}{name:QURQVG9rZW4=}{serial:Mg==}"
    method, req_path, body = "GET", "/1.0/library?num_results=10&page=1", ""

    headers = sign_request(
        method=method,
        path=req_path,
        body=body.encode(),
        adp_token=adp_token,
        private_key=private_pem,
    )
    signature, _, _ = headers["x-adp-signature"].rpartition(":")

    # sign_request stamps its own date, so re-sign the exact string with the
    # fixed date to give the test something reproducible to compare against.
    signed_string = f"{method}\n{req_path}\n{SIGN_DATE}\n{body}\n{adp_token}"
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding

    fixed_signature = base64.b64encode(
        key.sign(signed_string.encode(), padding.PKCS1v15(), hashes.SHA256())
    ).decode()

    vectors["signing"] = {
        "publicKeyPem": public_pem,
        "adpToken": adp_token,
        "method": method,
        "path": req_path,
        "body": body,
        "date": SIGN_DATE,
        "signedString": signed_string,
        "signature": fixed_signature,
        "algHeader": headers["x-adp-alg"],
        # Shape only — the live value carries a timestamp.
        "signatureHeaderSample": headers["x-adp-signature"][:8] + "...",
    }

    # --- Licence voucher --------------------------------------------------
    # Encrypt a known voucher with the scheme the package decrypts, then record
    # the ciphertext. If the TypeScript port derives the key differently, it
    # cannot recover the plaintext.
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    plaintext = json.dumps(
        {"key": "0123456789abcdef0123456789abcdef", "iv": "fedcba9876543210fedcba9876543210",
         "refresh_date": "2026-01-01", "rules": []}
    )
    padded = plaintext.encode() + b"\x00" * (-len(plaintext.encode()) % 16)
    digest = hashlib.sha256((DEVICE_TYPE + DEVICE_SERIAL + CUSTOMER_ID + ASIN).encode("ascii")).digest()
    encryptor = Cipher(algorithms.AES(digest[0:16]), modes.CBC(digest[16:])).encryptor()
    ciphertext = base64.b64encode(encryptor.update(padded) + encryptor.finalize()).decode()

    decrypted = _decrypt_voucher(
        device_serial_number=DEVICE_SERIAL,
        customer_id=CUSTOMER_ID,
        device_type=DEVICE_TYPE,
        asin=ASIN,
        voucher=ciphertext,
    )
    assert decrypted["key"] == "0123456789abcdef0123456789abcdef", "round-trip failed"

    vectors["voucher"] = {
        "deviceType": DEVICE_TYPE,
        "deviceSerial": DEVICE_SERIAL,
        "customerId": CUSTOMER_ID,
        "asin": ASIN,
        "encrypted": ciphertext,
        "decrypted": decrypted,
    }

    # --- The signature date format ---------------------------------------
    from datetime import UTC, datetime

    vectors["dateFormatExample"] = datetime.now(UTC).isoformat("T") + "Z"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(vectors, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}")


if __name__ == "__main__":
    main()
